import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import logo from '../../../assets/logo'; // Ensure this is a valid base64 string

const generatePDF = (data, filename, type, userName, startDate, endDate, selectedType) => {
    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    const imgWidth = 80; // Logo width
    const imgHeight = 20; // Logo height
    const xPos = (pageWidth - imgWidth) / 2; // Center horizontally
    const yPos = 10; // Position near the top of the page

    // Add logo
    doc.addImage(logo, 'PNG', xPos, yPos, imgWidth, imgHeight);

    // Add a line below the logo
    const lineY = yPos + imgHeight + 5; // Position for the line
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.line(10, lineY, pageWidth - 10, lineY); // Line below logo

    // Add spacing
    let yPosition = lineY + 10; // Space after line

    // Set font size and color for all text
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);

    // Add Username
    doc.text(`User: ${userName}`, 10, yPosition);

    // Add Transaction Type if applicable
    if (selectedType) {
        yPosition += 10;
        doc.text(`Transaction Type: ${selectedType}`, 10, yPosition);
    }

    // Add Time Period if applicable
    if (startDate && endDate) {
        yPosition += 10;
        doc.text(`Time Period: ${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`, 10, yPosition);
    }

    // Add title based on type
    yPosition += 20; // Space before title
    const title = type === 'wallet' ? 'Wallet Transactions' : 'Referral Logs';
    const titleWidth = doc.getStringUnitWidth(title) * doc.internal.getFontSize() / doc.internal.scaleFactor;
    const titleX = (pageWidth - titleWidth) / 2;
    doc.text(title, titleX, yPosition);

    // Update yPosition for the table
    yPosition += 10; // Space after title

    // Define table columns
    const columns = type === 'wallet'
        ? [
            { header: 'Date', dataKey: 'date' },
            { header: 'Description', dataKey: 'type' },
            { header: 'Amount', dataKey: 'amount' },
            { header: 'Status', dataKey: 'status' },
          ]
        : [
            { header: 'Date', dataKey: 'date' },
            { header: 'Referred User', dataKey: 'referredUserName' },
            { header: 'Status', dataKey: 'status' },
          ];

    // Map data to rows
    const rows = data.map(item => ({
        date: new Date(item.date).toLocaleDateString(),
        ...(type === 'wallet' ? {
            type: item.type,
            amount: `LKR ${item.amount}`,
            status: item.status || 'Success',
        } : {
            referredUserName: item.referredUserName,
            status: item.status || 'Success',
        }),
    }));

    // Generate the table
    doc.autoTable({
        columns,
        body: rows,
        startY: yPosition,
    });

    // Add autogenerated text at the bottom of the page
    const autoGenText = `This is an autogenerated PDF for ${userName} from Ceylon Odyssey on ${new Date().toLocaleDateString()}`;
    const autoGenYPos = doc.internal.pageSize.height - 20; // Position near the bottom
    doc.setTextColor(150, 150, 150); // Lighter color for autogenerated text
    doc.text(autoGenText, 10, autoGenYPos);

    // Save the document
    doc.save(filename);
};

export default generatePDF;
